In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv('./가게리스트_reviews_정제완료.csv')

In [6]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df.shape

(22782, 11)

In [7]:
df[df.Category1.isna()]

Empty DataFrame
Columns: [storeid, Title, storename, Region, Sigungu, search_area, Category1, Category2, menu, Blog, reviews_num]
Index: []

In [8]:
df.Category1.unique()

array(['한식', '중국식', '기타', '일식', '치킨', '서양식', '기타아시아식', '일반음식점', '기타외국음식',
       '아시아'], dtype=object)

In [30]:
len(df.Category2.sort_values().unique())

653

In [27]:
df.Category2.sort_values().unique()

array(['가라아게', '가마솥닭볶음탕', '가정식', '가정식백반', '간장게장', '갈매기살', '갈비',
       '갈비. 삼겹살/ 냉면', '갈비정식', '갈비찜', '갈비탕', '갈빗살', '갈치요리', '갈치조림',
       '갈치조림. 고등어조림', '감자국', '감자탕', '감자탕집', '강된장', '검정콩국수', '게', '게장',
       '계절정식', '고기', '고기구이', '고기구이/ 국밥', '고기구이/ 샤브샤브', '고기국수. 비빔국수',
       '고등어조림', '고래고기', '고로케/ 튀김/ 가라아게', '곤드레밥', '골뱅이', '골뱅이무침', '골뱅이뱅뱅',
       '곰치국', '곰탕', '곰탕/설렁탕', '곱창', '곱창/ 막창', '곱창전골', '과메기', '과일주스',
       '광어회', '국밥', '국밥/ 감자탕', '국수', '국수/ 국밥', '국수/ 죽', '굴구이', '굴국밥',
       '굴비정식', '굴요리전문', '규동', '그라탕', '김치두루치기두부', '김치말이국수', '김치찌개', '김치찜',
       '까페', '껍데기', '꼬리곰탕', '꼬막', '꼬막무침', '꼬막무침/ 통소라', '꼬막비빔밥/ 한우타다끼',
       '꼬치', '꽃게순두부', '꽃게탕', '꽃등심', '꿀빵', '꿔바로우', '나시고랭/ 미고랭', '낙지',
       '낙지볶음', '남도요리', '내장산산채한정식', '냉면', '냉면집', '농어회', '능이백숙코스', '다슬기',
       '다슬기탕/ 국밥', '다슬기해장국', '단란주점', '닭', '닭갈비', '닭강정', '닭강정/ 치즈닭꼬치',
       '닭개장', '닭곰탕', '닭국수', '닭꼬치', '닭도리탕', '닭발', '닭백숙', '닭볶음탕', '닭불고기',
       '닭한마리', '대게', '대게집', '대구', '대구막창', '대구머리찜', '대구뽈찜/ 뽈구이', '대구지리탕',
       '대구찜', '대구탕', '대방어회. 갈치조림', '대통밥', '대패삼겹살', '더덕정식', '덮밥', '도가니탕',
       '도넛', '도루묵/가자미찌개', '도시락', '도토리묵', '돈가스', '돈까스', '돈까스/ 스파게티',
       '돈까스/ 초계국수', '돈부리', '돈카츠', '돌솥밥', '동태찌개', '동태찜', '동태탕', '동파육',
       '돼지', '돼지갈비', '돼지고기', '돼지고기/ 주꾸미/ 냉면', '돼지고기구이/ 직화삼겹살/ 고등어김치찌개',
       '돼지고기정식', '돼지구이', '돼지국밥', '돼지막창', '돼지불고기', '돼지한마리', '된장찌개', '두루치기',
       '두루치기정식/육회비빔밥', '두부', '두부김치', '두부전골', '들깨 수제비', '들깨수제비', '등갈비',
       '등심', '등심돈까스', '디저트', '떡갈비', '떡볶이', '똠양꿍/ 팍붕', '뚝배기', '라멘',
       '라멘/ 돈코츠/ 차슈동', '라면', '라이브카페', '랍스타', '리조또/ 스테이크', '마늘약선정식', '마라탕',
       '막걸리/ 소고기전골', '막국수', '막창', '막창구이', '매생이국', '매운탕', '맥주', '맥주/ 치킨',
       '맥주/ 피자', '맥주/ 한치', '머밀전병', '메밀', '메밀국수', '메밀막국수',
       '멕시코요리/ 타코/ 퀘사디아', '면', '멸치국수', '멸치회/ 쌈밥정식', '명태', '명태조림', '명태찜',
       '모듬똥집', '모듬전', '모듬회', '모듬회등', '묵', '묵은지', '묵은지 닭토리탕', '묵은지감자탕',
       '묵은지닭매운탕', '물메기', '물회', '미역국', '미용실', '민물장어/간장게장', '민속주점', '민어탕',
       '밀냉면', '밀면', '바게트', '바베큐', '바지락죽', '반찬', '반찬가게', '밥', '밥버거', '방어회',
       '배춪ㄴ', '백반', '백숙', '버거', '버거/ 스테이크', '버섯요리', '버섯탕', '베이징덕/ 딤섬',
       '베이커리', '베트남음식', '벤댕이', '보리밥', '보말국. 보말칼국수', '보신탕', '보쌈', '복매운탕',
       '복샤브샤브', '복어', '복어요리', '복어요리/ 복매운탕', '복어탕', '복요리.시래기갈치고등어조림', '복탕',
       '복합문화공간', '볼테기탕', '봉골레파스타', '부대찌개', '부대찌게', '부르스케타', '분식', '불고기',
       '불고기 산채정식', '불고기/ 양대창구이', '불고기정식', '불낙전골', '불닭', '불백', '붕어찜', '뷔페',
       '브런치', '브런치/ 스테이크/ 스파게티', '브런치/ 파니니/ 샐러드', '비비큐', '비빔국수', '비빔밥',
       '비스트로', '빈대떡', '빠가사리매운탕', '뼈다귀', '뼈다귀감자탕', '뼈다귀해장국', '뽈때기찜', '뽈살',
       '사골', '사골옹심이', '사철탕', '산낙지비빔밥', '삼겹살', '삼계탕', '삼계탕/ 백숙', '삼합',
       '새우구이', '새우튀김', '샌드위치', '샐러드', '샐러드/ 스테이크', '샐러드/ 파스타/ 스테이크',
       '샐러드/ 파스타/ 스테이크/ 리조또', '생갈비 매운전골', '생고기', '생고기/ 삼겹살',
       '생고기/ 육회/ 곱창전골', '생고기구이', '생등심', '생삼겹', '생삼겹살', '생선', '생선구이',
       '생선모듬찜', '생선조림', '생선찜', '생선회', '생선회/ 오징어회/ 세꼬시', '생선회/초밥', '생태탕',
       '샤브샤브', '샤브샤브/월남쌈', '서양식코스요리', '석쇠구이/국밥', '섞어국밥', '설렁탕', '섭국',
       '세꼬시', '소갈비', '소갈비/ 냉면', '소고기', '소고기국밥', '소고기뭇국', '소곱창', '소국밥',
       '소금구이', '소머리국밥', '소바', '소불고기', '손칼국수', '송어', '송어회', '솥뚜껑닭볶음탕',
       '수구레국밥/소머리국밥', '수수부꾸미', '수육/ 국밥', '수육국밥', '수제버거', '수제비', '숙박시설',
       '순대', '순대/순대국', '순대국밥', '순두부', '순두부전골', '순두부찌개', '숯발닭갈비', '숯불갈비',
       '숯불고기', '숯불구이', '숯불닭갈비', '스테이크', '스테이크/ 파스타', '스테이크/ 필라프', '스파게티',
       '스파게티/ 파스타', '스파게티/ 피자', '스페인요리/ 와인/ 홍합스튜', '스페인코스요리/ 타파스', '시골밥상',
       '시래기국밥', '쌀국수', '쌀국수/ 반쎄오', '쌀국수/ 분짜', '쌀국수/ 짜조', '쌈밥',
       '쌈정식/ 코다리정식/ 약채정식', '쌈제육정식', '쏘가리탕', '아구찜', '아나고탕', '아메리카노',
       '아메리카노/ 단호박라떼', '아메리카노/ 라떼', '아메리카노/ 에스프레소', '아메리카노/ 카페라떼',
       '아메리카노/ 쿠키', '아메리카노/ 크림생맥주', '아이스크림', '아이스크림호떡', '알수없음', '야끼규동정식',
       '야식집', '약쑥시레기밥', '약채밥상', '양갈비', '양고기', '양곱창', '양꼬치', '양념갈비',
       '양념돼지갈비', '양념불고기', '양푼갈비', '양푼동태탕', '어복탕', '연어덮밥/ 스테이크덮밥', '염소탕',
       '영양돌솥밥', '영양솥밥', '영양탕', '옛날삼겹살', '옛날통닭', '오겹살', '오겹살/ 항정살', '오골계탕',
       '오꼬노미야끼', '오돌뼈', '오리', '오리구이', '오리매운탕', '오리백숙', '오리주물럭', '오징어',
       '오징어 보쌈', '오코노미야끼', '올갱이', '올갱이해장국', '옹심이', '옻닭', '옻닭백숙', '와규/ 막창',
       '와인', '와인/ 칵테일', '와인/ 파스타/ 스테이크/ 브런치', '완당', '왕갈비', '우동', '우럭회',
       '우렁쌈밥정식', '우렁이쌈밥', '우육면', '울금떡갈비정식/ 버섯불고기정식', '월남쌈', '월남쌈/ 샤브샤브',
       '웨딩홀', '유원지', '육개장', '육회', '육회비빔밥', '이벤트홀', '이자카야', '이자카야/ 매콤크림새우',
       '이탈리아코스요리', '이탈리아코스요리/ 샐러드/ 파스타', '이탈리안', '인도/ 태국', '인도/태국',
       '인도요리/ 치킨커리', '인도요리/ 커리', '인도요리/ 커리/ 탄두리치킨', '인삼정식+삼계탕', '잉어찜',
       '자연산버섯찌개', '잔치국수', '잣두부전골', '장닭', '장어', '장어구이', '장어요리', '장어주물럭',
       '장어탕/ 된장찌개', '장어탕/전복탕/장어구이', '장치찜', '장칼국수', '장터국밥', '장터국수', '재육볶음',
       '전', '전골', '전골류', '전복', '전복뚝배기. 조림', '전복죽', '전복코스요리', '전주비빔밥',
       '전통찻집', '젓국갈비', '정식코스', '정종/대포집/소주방', '제과', '제육볶음', '조개', '조개구이',
       '조개모듬구이', '조개및삼겹살구이', '조개찜', '족발', '족발/보쌈', '족발/보쌈/치킨', '주류',
       '주류/ 오뎅탕', '주먹고기', '주점', '죽', '짜글이찌개', '짜장', '짜장. 짬뽕', '짜장면',
       '짜장면/ 짬뽕', '짜짱면', '짬뽕', '쭈꾸미', '찌개', '찜', '찜닭', '찜닭/치킨/똥집',
       '참복국/ 복매운탕', '참숯갈비', '참치', '참치/ 참가자미', '채식요리/ 불구이쌈밥', '철판구이',
       '철판스테이크', '청국장', '청국장정식', '초당순두부', '초밥', '초밥/ 생연어', '초밥/ 스시',
       '추어탕', '치밥', '치킨', '카레', '카레/ 오야코동', '카페', '칵테일', '칵테일/ 와인/ 샐러드',
       '칼국수', '칼국수/ 수육', '캠핑장', '커트', '커피', '커피/ 과일청/ 꿀빵',
       '커피/ 더치커피/ 자몽주스', '커피/ 돈까스', '커피/ 돌체라떼', '커피/ 버거/ 샌드위치/ 샐러드',
       '커피/ 브런치/ 토스트', '커피/ 샐러드/ 쿠키', '커피/ 스테이크', '커피/ 아메리카노/ 라떼',
       '커피/ 아메리카노/ 모히토', '커피/ 아메리카노/ 크로와상샌드위치', '커피/ 에스프레소/ 당근케이크',
       '커피/ 에클레어', '커피/ 타르트', '커피/ 파스타', '커피프라푸치노', '케밥', '코다리', '코다리찜',
       '콩나물국밥', '퀘사디아/ 또띠아', '큐브스테이크/ 와인', '크랩', '크리스피치킨/ 순살치킨', '타코',
       '탄두리치킨/ 버터치킨카레', '탕', '탕수육', '탕수육집', '태국요리', '태국요리/ 갈비국수/ 팟타이',
       '태국요리전문', '터키음식/ 케밥', '터키음식/ 케밥/ 터키식치킨스테이크', '테마파크', '토스트', '토종닭',
       '튀김', '파니니/ 파스타', '파스타', '파스타/ 돈까스', '파스타/ 라따뚜이', '파스타/ 리조또/ 샐러드',
       '파스타/ 물냉면', '파스타/ 스테이크', '파스타/ 스테이크/ 피자', '파스타/ 피자',
       '파스타/ 피자/ 스테이크', '파스타/ 필라프', '파전', '팔도면요리', '팟타이/ 똠양꿍', '팟타이/ 쌀국수',
       '팥죽', '패스트푸드', '펜션', '포장마차', '포차', '풀빌라', '프랑스코스요리', '피자',
       '피자/ 리조또/ 맥주', '피자/ 맥주', '피자/ 스테이크', '피자/ 파스타', '피자/ 파스타/ 리조또',
       '피자집', '필라프', '하모 샤브샤브', '하버돈가스', '하얀초당순두부', '한방백숙', '한우 한돈',
       '한우/ 소고기', '한우고기', '한우구이/한우불고기', '한우국밥', '한우등심', '한우등심/ 돼지고기 등',
       '한우떡갈비', '한우불고기/ 꽃등심', '한우불고기/한우등심', '한우생갈비', '한우생등심', '한우숯불떡갈비',
       '한정식', '한정식/ 한우육개장', '한정식/꽃게장', '함박스테이크', '핫도그', '해물', '해물뚝배기',
       '해물요리', '해물전골', '해물찜', '해물칼국수', '해물탕', '해물탕/ 회', '해물파전', '해산물',
       '해산물찜', '해산물한정식', '해장국', '햄버거', '현미채식', '호떡', '호프', '호프/통닭', '홍게',
       '홍어', '화덕피자/ 수제파스타', '화로구이', '활어', '활어회', '활어회.매운탕', '활어회/ 매운탕',
       '황태', '황태구이', '황태구이백반', '황태콩나물', '회', '회/ 전복회', '회냉면', '회덮밥',
       '회무침', '회정식', '회집', '회춘탕', '훠궈', '흑돼지구이', '흑돼지구이. 갈비탕',
       '흑돼지구이. 김치찌개', '흑돼지구이. 동치미국수', '흑돼지구이. 해물찜', '흑염소전골'], dtype=object)

In [17]:
# 현재 '알수없음'으로 분류된 카테고리2 12,216개, 최대한 채운다.
df[df.Category2=='알수없음'].shape

(12216, 11)

In [18]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('국수') != -1)].index
df.loc[idxs, 'Category2'] = '국수'

In [19]:
df[df.Category2=='알수없음'].shape

(12055, 11)

In [21]:
idxs = df[(df.Category2=='국수') & (df.storename.str.find('쌀국수') != -1)].index
len(idxs)

10

In [22]:
df.loc[idxs, 'Category2'] = '쌀국수'

In [23]:
df[(df.Category2=='알수없음') & (df.storename.str.find('회집') != -1)]

,storeid,Title,storename,Region,Sigungu,search_area,Category1,Category2,menu,Blog,reviews_num
427,15518,서해바다회집,서해바다회집,전라북도,군산시,군산,한식,알수없음,알수없음,178,1
2413,182333,삼호회집,삼호회집,인천,강화군,강화,한식,알수없음,알수없음,77,2
2447,182108,양도회집,양도회집,인천,강화군,강화,한식,알수없음,알수없음,503,26
3499,178561,남해회집,남해회집,인천,계양구,계양,한식,알수없음,알수없음,350,1
3691,162724,유명한회집,유명한회집,서울,관악구,관악,한식,알수없음,알수없음,89,8
4301,98320,부부회집,부부회집,경기도,구리시,구리,한식,알수없음,알수없음,118,8
5986,168487,동해막회집,동해막회집,인천,동구,인천,한식,알수없음,알수없음,163,9
10843,149700,등대회집,등대회집,경상북도,문경시,문경,한식,알수없음,알수없음,44,2
12959,161691,석촌회집,석촌회집,경기도,성남시,성남,한식,알수없음,알수없음,60,1
13165,109626,광교회집,광교회집,경기도,수원시,수원,한식,알수없음,알수없음,223,5
13263,110155,독도회집,독도회집,경기도,수원시,수원,한식,알수없음,알수없음,85,5
13468,112786,청명회집,청명회집,경기도,수원시,수원,한식,알수없음,알수없음,82,1
13631,110888,보라회집,보라회집,경기도,수원시,수원,한식,알수없음,알수없음,103,4
14049,114227,서해바다회집 양념코너 식당,서해바다회집양념코너식당,경기도,시흥시,시흥,한식,알수없음,알수없음,758,41
14790,119766,부산회집,부산회집,경기도,안양시,안양,한식,알수없음,알수없음,707,13
15121,122440,강남회집,강남회집,경기도,양평군,양평,한식,알수없음,알수없음,432,1
16049,183096,대성회집,대성회집,인천,옹진군,옹진,한식,알수없음,알수없음,195,1
19043,11841,막내네회집,막내네회집,서울,중구,서울,한식,알수없음,알수없음,763,110
19399,167164,털보회집,털보회집,인천,중구,인천,한식,알수없음,알수없음,79,2
19524,167464,먹고보자 호남회집,먹고보자호남회집,인천,중구,인천,한식,알수없음,알수없음,1679,145
19617,167857,미락회집,미락회집,인천,중구,인천,한식,알수없음,알수없음,97,5
19735,167177,부산항구회집,부산항구회집,인천,중구,인천,한식,알수없음,알수없음,113,3
19822,12240,생생회집,생생회집,서울,중구,서울,한식,알수없음,알수없음,389,76
19845,167053,서해회집,서해회집,인천,중구,인천,한식,알수없음,알수없음,545,73
19855,167463,섬마을청정회집,섬마을청정회집,인천,중구,인천,한식,알수없음,알수없음,8167,56
20824,133606,내고향회집,내고향회집,경기도,평택시,평택,한식,알수없음,알수없음,89,2
21241,134256,소문난회집,소문난회집,경기도,평택시,평택,한식,알수없음,알수없음,75,5
22083,137854,궁평낙조회집,궁평낙조회집,경기도,화성시,화성,한식,알수없음,알수없음,27,1
22198,138408,만선회집,만선회집,경기도,화성시,화성,한식,알수없음,알수없음,33,2
22200,138415,만찬회집,만찬회집,경기도,화성시,화성,한식,알수없음,알수없음,22,1
22588,139003,속초회집,속초회집,경기도,화성시,화성,한식,알수없음,알수없음,292,3
22613,139075,수원회집,수원회집,경기도,화성시,화성,한식,알수없음,알수없음,585,13
22632,139145,신선회집,신선회집,경기도,화성시,화성,한식,알수없음,알수없음,125,16
22639,139146,신성회집,신성회집,경기도,화성시,화성,한식,알수없음,알수없음,85,2

In [28]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('회집') != -1)].index
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

In [91]:
df[(df.Category2=='알수없음') & (df.storename.str.find('찻집') != -1)]

,storeid,Title,storename,Region,Sigungu,search_area,Category1,Category2,menu,Blog,reviews_num
536,15819,호수가찻집,호수가찻집,전라북도,군산시,군산,한식,알수없음,알수없음,384,13
4569,117867,다래 전통찻집,다래전통찻집,경기도,안성시,안성,한식,알수없음,알수없음,30,5

In [31]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('돼지') != -1)].index
df.loc[idxs, 'Category2'] = '돼지구이'
df.loc[idxs, 'menu'] = '돼지구이'

In [34]:
idxs = df[(df.storename.str.find('돼지') != -1)&(df.storename.str.find('곱창') != -1)].index
df.loc[idxs, 'Category2'] = '곱창'
df.loc[idxs, 'menu'] = '돼지곱창'

In [36]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('가든') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

In [37]:
df[df.Category2=='알수없음']

,storeid,Title,storename,Region,Sigungu,search_area,Category1,Category2,menu,Blog,reviews_num
14,14029,위,위,전라남도,광양시,광양,기타,알수없음,알수없음,7040,57
16,14044,랑,랑,전라남도,광양시,광양,기타,알수없음,알수없음,3307,2
22,14063,미리소주방,미리소주방,전라남도,광양시,광양,기타,알수없음,알수없음,16,1
24,14066,광양계란집,광양계란집,전라남도,광양시,광양,기타,알수없음,알수없음,4934,161
30,14076,디스,디스,전라남도,광양시,광양,기타,알수없음,알수없음,33,1
32,14079,망고,망고,전라남도,광양시,광양,기타,알수없음,알수없음,225,12
44,14107,묵자,묵자,전라남도,광양시,광양,한식,알수없음,알수없음,18,1
53,14128,밤부엉이,밤부엉이,전라남도,광양시,광양,한식,알수없음,알수없음,205,1
81,14207,동일음식점,동일음식점,전라남도,광양시,광양,한식,알수없음,알수없음,485,7
91,14226,해운식당,해운식당,전라남도,광양시,광양,한식,알수없음,알수없음,284,1
96,14239,섬진식당,섬진식당,전라남도,광양시,광양,한식,알수없음,알수없음,1939,23
101,14248,옛마당식당,옛마당식당,전라남도,광양시,광양,한식,알수없음,알수없음,832,2
103,14259,백운마루,백운마루,전라남도,광양시,광양,한식,알수없음,알수없음,752,1
105,14264,미식가회관,미식가회관,전라남도,광양시,광양,한식,알수없음,알수없음,119,2
108,14268,유신이네,유신이네,전라남도,광양시,광양,한식,알수없음,알수없음,1300,4
114,14280,앵두나무집,앵두나무집,전라남도,광양시,광양,한식,알수없음,알수없음,240,13
122,14295,가나식당,가나식당,전라남도,광양시,광양,한식,알수없음,알수없음,916,64
128,14305,저녁마당,저녁마당,전라남도,광양시,광양,한식,알수없음,알수없음,2414,32
129,14308,행복이있는곳에,행복이있는곳에,전라남도,광양시,광양,한식,알수없음,알수없음,18651,25
131,14313,술이술이,술이술이,전라남도,광양시,광양,한식,알수없음,알수없음,22526,99
139,14335,호롱식당,호롱식당,전라남도,광양시,광양,한식,알수없음,알수없음,152,6
146,14350,옥곡식당,옥곡식당,전라남도,광양시,광양,한식,알수없음,알수없음,442,18
152,14363,대륙식당,대륙식당,전라남도,광양시,광양,한식,알수없음,알수없음,289,1
158,14378,가보자 맛집,가보자맛집,전라남도,광양시,광양,한식,알수없음,알수없음,1028,64
171,14401,텃밭식당,텃밭식당,전라남도,광양시,광양,한식,알수없음,알수없음,467,19
173,14405,맛집가온,맛집가온,전라남도,광양시,광양,한식,알수없음,알수없음,83,2
174,14409,매화마을,매화마을,전라남도,광양시,광양,한식,알수없음,알수없음,815,7
175,14412,옥룡고향집,옥룡고향집,전라남도,광양시,광양,한식,알수없음,알수없음,187,4
178,14418,손맛나는세상,손맛나는세상,전라남도,광양시,광양,한식,알수없음,알수없음,181,5
180,14421,궁만식당,궁만식당,전라남도,광양시,광양,한식,알수없음,알수없음,707,10
...,...,...,...,...,...,...,...,...,...,...,...
22651,139209,앨리스1865,앨리스1865,경기도,화성시,화성,한식,알수없음,알수없음,20,3
22655,139210,야끼,야끼,경기도,화성시,화성,한식,알수없음,알수없음,65,15
22656,139212,야망,야망,경기도,화성시,화성,한식,알수없음,알수없음,2726,12
22657,139217,양념코너1호집,양념코너1호집,경기도,화성시,화성,한식,알수없음,알수없음,3268,192
22658,139219,양노리식당,양노리식당,경기도,화성시,화성,한식,알수없음,알수없음,84,2
22660,139228,양파식당,양파식당,경기도,화성시,화성,한식,알수없음,알수없음,3176,197
22662,139247,어부네꽃게마을,어부네꽃게마을,경기도,화성시,화성,한식,알수없음,알수없음,2481,1
22663,139248,어부와명태,어부와명태,경기도,화성시,화성,한식,알수없음,알수없음,106,2
22664,139254,어섬식당,어섬식당,경기도,화성시,화성,한식,알수없음,알수없음,88,11
22665,139260,어촌마을,어촌마을,경기도,화성시,화성,한식,알수없음,알수없음,44,5
22667,139264,엄나무집,엄나무집,경기도,화성시,화성,한식,알수없음,알수없음,367,92
22671,165423,고구려민속촌,고구려민속촌,전라남도,화순군,화순,한식,알수없음,알수없음,92,13
22675,164769,바다회센터,바다회센터,강원도,화천군,화천,한식,알수없음,알수없음,567,17
22676,162218,장미산장,장미산장,강원도,횡성군,횡성,한식,알수없음,알수없음,229,27
22682,100371,엄마네밥상,엄마네밥상,경기도,김포시,김포,한식,알수없음,알수없음,2860,283
22683,162679,함포고복,함포고복,강원도,횡성군,횡성,한식,알수없음,알수없음,94,23
22691,100372,엄마맘,엄마맘,경기도,김포시,김포,한식,알수없음,알수없음,15,2
22692,152819,엄마밥상&낭만족발,엄마밥상&낭만족발,경상남도,거제시,거제,한식,알수없음,알수없음,1671,228
22699,167964,엄마세상,엄마세상,인천,중구,인천,한식,알수없음,알수없음,21,4
22714,114416,엄마손맛밥상,엄마손맛밥상,경기도,시흥시,시흥,한식,알수없음,알수없음,139,8
22716,132494,엄마손맛식당,엄마손맛식당,경기도,파주시,파주,한식,알수없음,알수없음,567,75
22718,174734,엄마손밥상,엄마손밥상,인천,남동구,남동,한식,알수없음,알수없음,4214,7
22719,94132,엄마손밥집,엄마손밥집,경기도,고양시,고양,한식,알수없음,알수없음,236,27
22741,121845,엄마외가,엄마외가,경기도,양주시,양주,한식,알수없음,알수없음,497,87
22746,105054,엄마의정성,엄마의정성,경기도,부천시,부천,한식,알수없음,알수없음,8491,201
22747,111788,엄마찬,엄마찬,경기도,수원시,수원,한식,알수없음,알수없음,35,14
22749,147757,엄마하고나하고,엄마하고나하고,경상북도,상주시,상주,한식,알수없음,알수없음,39478,260
22750,166301,엄바위,엄바위,제주도,제주시,제주,한식,알수없음,알수없음,17,2
22763,159308,업,업,서울,동대문구,동대문,한식,알수없음,알수없음,15837,51
22767,90342,엉클스게스트하우스,엉클스게스트하우스,강원도,춘천시,춘천,기타,알수없음,알수없음,25,3

In [39]:
df[(df.Category2=='알수없음') & (df.storename.str.find('식당') != -1)].shape

(1967, 11)

In [40]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('식당') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

In [41]:
df[(df.Category2=='알수없음') & (df.storename.str.find('밥상') != -1)].shape

(230, 11)

In [42]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('밥상') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

In [43]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('회관') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

In [45]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('밥집') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

In [47]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('고향집') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

8

In [48]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('음식점') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

8

In [49]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('회센터') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

3

In [62]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('회센타') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

8

In [70]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('어촌') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

9

In [50]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('곱창') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '곱창'
df.loc[idxs, 'menu'] = '곱창'

101

In [53]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('소주방') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주점'
df.loc[idxs, 'menu'] = '주점'

2

In [55]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('명태') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '명태'
df.loc[idxs, 'menu'] = '명태'

14

In [56]:
df[(df.Category2=='알수없음') & (df.storename.str.find('엄마') != -1)]

,storeid,Title,storename,Region,Sigungu,search_area,Category1,Category2,menu,Blog,reviews_num
3450,148975,엄마네 손맛,엄마네손맛,경상북도,경산시,경산,한식,알수없음,알수없음,533,124
4311,98476,엄마국시,엄마국시,경기도,구리시,구리,한식,알수없음,알수없음,355,74
11704,144826,울엄마간식,울엄마간식,부산,사상구,사상,한식,알수없음,알수없음,707,117
12394,82466,착한엄마손맛,착한엄마손맛,대전,서구,대전,한식,알수없음,알수없음,166,42
13843,111770,엄마네가자,엄마네가자,경기도,수원시,수원,한식,알수없음,알수없음,13927,285
14945,122221,친정엄마,친정엄마,경기도,양주시,양주,한식,알수없음,알수없음,114,4
16734,142106,예쁜엄마,예쁜엄마,울산,울주군,울주,한식,알수없음,알수없음,435,80
20981,133897,맛집엄마손,맛집엄마손,경기도,평택시,평택,한식,알수없음,알수없음,3027,220
22258,139486,원조엄마네,원조엄마네,경기도,화성시,화성,한식,알수없음,알수없음,15,1
22691,100372,엄마맘,엄마맘,경기도,김포시,김포,한식,알수없음,알수없음,15,2
22699,167964,엄마세상,엄마세상,인천,중구,인천,한식,알수없음,알수없음,21,4
22741,121845,엄마외가,엄마외가,경기도,양주시,양주,한식,알수없음,알수없음,497,87
22746,105054,엄마의정성,엄마의정성,경기도,부천시,부천,한식,알수없음,알수없음,8491,201
22747,111788,엄마찬,엄마찬,경기도,수원시,수원,한식,알수없음,알수없음,35,14
22749,147757,엄마하고나하고,엄마하고나하고,경상북도,상주시,상주,한식,알수없음,알수없음,39478,260

In [57]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('엄마') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

15

In [64]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('언니') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

16

In [72]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('집밥') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

57

In [77]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('한식') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

71

In [87]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('맛집') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

71

In [89]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('손맛') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

6

In [60]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('꽃게') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '꽃게'
df.loc[idxs, 'menu'] = '꽃게'

6

In [68]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('술') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주점'
df.loc[idxs, 'menu'] = '주류'

59

In [75]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('닭') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '닭'
df.loc[idxs, 'menu'] = '닭'

83

In [80]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('김치찜') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '김치찜'
df.loc[idxs, 'menu'] = '김치찜'

2

In [82]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('맥주') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주점'
df.loc[idxs, 'menu'] = '맥주/주류'

26

In [84]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('한잔') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주점'
df.loc[idxs, 'menu'] = '맥주/주류'

16

In [92]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('연탄') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

13

In [116]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('숯불') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '숯불구이'

8

In [123]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('화로') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '화로구이'

37

In [96]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('이베리코') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '돼지구이'
df.loc[idxs, 'menu'] = '돼지구이'

1

In [131]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('석쇠') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '석쇠구이'

9

In [94]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('찻집') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '찻집'
df.loc[idxs, 'menu'] = '차'

2

In [103]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('화수목') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '한정식'
df.loc[idxs, 'menu'] = '한정식'

1

In [108]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('뼈다귀') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '뼈해장국'
df.loc[idxs, 'menu'] = '뼈해장국'

6

In [111]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('까스') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '돈까스'
df.loc[idxs, 'menu'] = '돈까스'

4

In [113]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('부페') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '뷔페'
df.loc[idxs, 'menu'] = '한식뷔페'

12

In [119]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('카레') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타아시아식'
df.loc[idxs, 'Category2'] = '카레'
df.loc[idxs, 'menu'] = '카레'

9

In [121]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('막창') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '막창'
df.loc[idxs, 'menu'] = '막창,곱창'

34

In [126]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('해물') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '해물'

20

In [129]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('마라탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '중국식'
df.loc[idxs, 'Category2'] = '마라탕'
df.loc[idxs, 'menu'] = '마라탕'

6

In [134]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('굴비') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '굴비'
df.loc[idxs, 'menu'] = '굴비구이'

1

In [138]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('보쌈') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '보쌈'
df.loc[idxs, 'menu'] = '보쌈,족발'

15

In [140]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('보신탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '보신탕'
df.loc[idxs, 'menu'] = '보신탕'

13

In [145]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('코다리') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '코다리'
df.loc[idxs, 'menu'] = '코다리'

19

In [147]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('낭만') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주점'
df.loc[idxs, 'menu'] = '주점'

6

In [150]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('과메기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '과메기'
df.loc[idxs, 'menu'] = '과메기'

1

In [152]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('버섯') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '버섯'
df.loc[idxs, 'menu'] = '버섯전골'

15

In [154]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('능이') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '버섯'
df.loc[idxs, 'menu'] = '버섯전골'

2

In [158]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('동태') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '동태'
df.loc[idxs, 'menu'] = '동태'

22

In [161]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('샤브') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '샤브샤브'
df.loc[idxs, 'menu'] = '샤브샤브'

28

In [165]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('국시') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '국수'
df.loc[idxs, 'menu'] = '국수'

28

In [167]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('돈') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '돼지'
df.loc[idxs, 'menu'] = '돼지'

70

In [169]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('전집') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '전'
df.loc[idxs, 'menu'] = '전'

15

In [171]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('떡볶기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '분식'
df.loc[idxs, 'menu'] = '떡볶이'

4

In [176]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('스파게티') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '스파게티'
df.loc[idxs, 'menu'] = '스파게티'

2

In [178]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('뚝배기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '찌개'
df.loc[idxs, 'menu'] = '찌개'

18

In [180]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('세꼬시') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '세꼬시, 회'

5

In [184]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('라면') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '라면'
df.loc[idxs, 'menu'] = '라면'

13

In [188]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('레스토랑') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '스테이크'
df.loc[idxs, 'menu'] = '파스타,스테이크'

50

In [192]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('마마') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '스테이크'
df.loc[idxs, 'menu'] = '파스타,스테이크'

7

In [194]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('마미') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '스테이크'
df.loc[idxs, 'menu'] = '파스타,스테이크'

2

In [196]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('해산') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '해물요리'

1

In [199]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('고향') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

31

In [201]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('껍데기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '껍데기'
df.loc[idxs, 'menu'] = '돼지껍데기'

4

In [203]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('전복') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '전복'

11

In [205]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('찌게') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '찌개'
df.loc[idxs, 'menu'] = '찌개'

8

In [208]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('참죽') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '죽'
df.loc[idxs, 'menu'] = '죽'

1

In [210]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('수제비') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '수제비'
df.loc[idxs, 'menu'] = '수제비'

7

In [212]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('그릴') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

10

In [214]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('맛나') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '분식'
df.loc[idxs, 'menu'] = '김밥'

13

In [216]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('맘스') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '햄버거'
df.loc[idxs, 'menu'] = '햄버거'

7

In [219]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('경양식') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '경양식'
df.loc[idxs, 'menu'] = '경양식'

10

In [221]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('맛있는') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

20

In [223]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('메밀') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '메밀국수'
df.loc[idxs, 'menu'] = '메밀국수'

23

In [230]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('빈대떡') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '빈대떡'
df.loc[idxs, 'menu'] = '빈대떡'

16

In [233]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('갈비') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '갈비'
df.loc[idxs, 'menu'] = '갈비'

11

In [237]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('김선생') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '분식'
df.loc[idxs, 'menu'] = '김밥'

3

In [238]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('킹크랩') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '킹크랩'

1

In [239]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('가재') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '바닷가재'

2

In [241]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('곰탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '곰탕'
df.loc[idxs, 'menu'] = '곰탕'

10

In [244]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('밥') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

88

In [246]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('어시장') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

12

In [248]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('번개') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

4

In [250]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('주점') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주류'
df.loc[idxs, 'menu'] = '주류'

3

In [252]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('꼬막') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '꼬막'

1

In [254]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('고깃') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

13

In [261]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('북경') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '중국식'
df.loc[idxs, 'Category2'] = '짜장면'
df.loc[idxs, 'menu'] = '짬뽕'

2

In [263]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('생선') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '생선'
df.loc[idxs, 'menu'] = '생선구이'

8

In [265]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('북어') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '생선'
df.loc[idxs, 'menu'] = '북어'

3

In [268]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('비비큐') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '바베큐'

1

In [273]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('생태') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '생태'
df.loc[idxs, 'menu'] = '생태탕'

6

In [275]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('삼합') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '삼합'
df.loc[idxs, 'menu'] = '삼합'

4

In [278]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('내장탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '내장탕'
df.loc[idxs, 'menu'] = '내장탕'

1

In [280]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('선지') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '선지국'
df.loc[idxs, 'menu'] = '선지국'

2

In [284]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('대구') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '대구'
df.loc[idxs, 'menu'] = '대구탕'

4

In [285]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('불백') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '불백'
df.loc[idxs, 'menu'] = '불백'

4

In [287]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('소바') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '소바'
df.loc[idxs, 'menu'] = '소바'

5

In [290]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('찜') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '찜'
df.loc[idxs, 'menu'] = '찜'

12

In [292]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('갈매') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '갈매기살'

19

In [294]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('소주') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '주류'
df.loc[idxs, 'menu'] = '소주'

3

In [298]:
df[df.Category2=='알수없음'].shape

(7724, 11)

In [303]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('어부') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

21

In [312]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('월수금') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '한정식'
df.loc[idxs, 'menu'] = '한정식'

3

In [314]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('이화수') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '육개장'
df.loc[idxs, 'menu'] = '육개장'

1

In [316]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('본가') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

33

In [317]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('명가') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

33

In [318]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('이네') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '백반'
df.loc[idxs, 'menu'] = '백반'

128

In [321]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('생고기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

11

In [323]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('감자탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '감자탕'
df.loc[idxs, 'menu'] = '감자탕'

10

In [325]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('영양탕') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '영양탕'
df.loc[idxs, 'menu'] = '영양탕'

8

In [327]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('고기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

22

In [329]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('갈치') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '갈치'
df.loc[idxs, 'menu'] = '갈치'

5

In [331]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('제육') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '제육볶음'
df.loc[idxs, 'menu'] = '제육볶음'

2

In [334]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('황태') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '황태'
df.loc[idxs, 'menu'] = '황태'

4

In [337]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('오징어') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '오징어'

12

In [341]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('도너츠') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '도넛'
df.loc[idxs, 'menu'] = '도넛'

3

In [346]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('오겹살') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '오겹살'

2

In [348]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('굴') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물'
df.loc[idxs, 'menu'] = '굴'

16

In [351]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('구이') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '고기구이'

58

In [353]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('주물') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '주물럭'
df.loc[idxs, 'menu'] = '주물럭'

3

In [356]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('철판') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '철판구이'

2

In [358]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('소한') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
df.loc[idxs, 'menu'] = '소고기'

9

In [360]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('바다') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'
df.loc[idxs, 'menu'] = '회'

65

In [362]:
idxs = df[(df.Category2=='알수없음') & (df.storename.str.find('테이블') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '스테이크'
df.loc[idxs, 'menu'] = '파스타'

17

In [394]:
df[df.Category2 == '알수없음'].shape

(7256, 11)

In [419]:
df.groupby('Category1').storeid.count()

Category1
기타         1161
기타아시아식       79
기타외국음식        8
서양식         529
일반음식점       218
일식         1201
중국식         338
치킨          317
한식        18931
Name: storeid, dtype: int64

### 기타아시아식 카테고리 정제

In [402]:
idxs = df[df.Category2 == '나시고랭/ 미고랭'].index
df.loc[idxs, 'Category2'] = '인도네시아'
idxs = df[df.Category2 == '똠양꿍/ 팍붕'].index
df.loc[idxs, 'Category2'] = '태국요리'

In [417]:
for ca in ['갈비','알수없음']:
    idxs = df[(df.Category1 == '기타아시아식') & (df.Category2 == ca)].index
    df.loc[idxs, 'Category2'] = '터키'

In [414]:
for ca in ['퀘사디아/ 또띠아','터키음식/ 케밥/ 터키식치킨스테이크','크랩','파스타/ 스테이크/ 피자'
           ,'터키음식/ 케밥/ 터키식치킨스테이크','스테이크','케밥','우육면']:
    idxs = df[df.Category2 == ca].index
    df.loc[idxs, 'Category2'] = '터키'

In [404]:
idxs = df[df.Category2 == '쌀국수/ 반쎄오'].index
df.loc[idxs, 'Category2'] = '쌀국수'
idxs = df[df.Category2 == '쌀국수/ 분짜'].index
df.loc[idxs, 'Category2'] = '쌀국수'
idxs = df[df.Category2 == '쌀국수/ 짜조'].index
df.loc[idxs, 'Category2'] = '쌀국수'

In [408]:
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('인도') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '인도'
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('태국') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '태국'

10
4

In [410]:
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('카레') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '인도'
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('샤브') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '베트남'
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('베트남') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '베트남'
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('쌀국수') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '베트남'

17
13
15
21

In [421]:
idxs = df[(df.Category1=='기타외국음식') & (df.Category2.str.find('인도') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타아시아식'
df.loc[idxs, 'Category2'] = '인도'
idxs = df[(df.Category1=='기타외국음식') & (df.Category2.str.find('카레') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타아시아식'
df.loc[idxs, 'Category2'] = '인도'
idxs = df[(df.Category1=='기타외국음식') & (df.Category2.str.find('케타') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '기타아시아식'
df.loc[idxs, 'Category2'] = '태국'

6
1
1

In [453]:
idxs = df[(df.Category1=='기타아시아식') & (df.Category2.str.find('터키') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '터키'

12

In [469]:
df[df.Category1 == '기타아시아식'].groupby('Category2').storeid.count()

Category2
베트남    36
인도     34
태국      6
Name: storeid, dtype: int64

In [423]:
df.groupby('Category1').storeid.count()

Category1
기타         1161
기타아시아식       87
서양식         529
일반음식점       218
일식         1201
중국식         338
치킨          317
한식        18931
Name: storeid, dtype: int64

### 중국식 카테고리 정제

In [424]:
df[df.Category1 == '중국식'].groupby('Category2').storeid.count()

Category2
꿔바로우          1
동파육           1
마라탕          10
베이징덕/ 딤섬      1
샤브샤브          1
알수없음          2
양고기           1
양꼬치          93
짜장            1
짜장. 짬뽕        1
짜장면          52
짜장면/ 짬뽕     108
짜짱면           1
짬뽕           54
탕수육           8
탕수육집          1
훠궈            2
Name: storeid, dtype: int64

In [425]:
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('짜') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '짜장면/ 짬뽕'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('짬') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '짜장면/ 짬뽕'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('양고기') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '양꼬치'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('꿔바로우') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '마라탕'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('샤브') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '마라탕'

163
217
1
1
1

In [427]:
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('육') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '탕수육'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('훠궈') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '탕수육'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('알수없음') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '탕수육'
idxs = df[(df.Category1=='중국식') & (df.Category2.str.find('딤섬') != -1)].index
print(len(idxs))
df.loc[idxs, 'Category2'] = '탕수육'

10
2
2
1

In [428]:
df[df.Category1 == '중국식'].groupby('Category2').storeid.count()

Category2
마라탕         12
양꼬치         94
짜장면/ 짬뽕    217
탕수육         15
Name: storeid, dtype: int64

### 일식 카테고리 정제

In [429]:
df[df.Category1 == '일식'].groupby('Category2').storeid.count()

Category2
가라아게                1
고로케/ 튀김/ 가라아게       1
광어회                 2
규동                  1
농어회                 1
도시락                 1
돈가스                21
돈까스               104
돈부리                 3
돈카츠                11
라멘                 18
라멘/ 돈코츠/ 차슈동        1
랍스타                 1
메밀국수                1
면                   1
모듬회등                1
물회                  4
방어회                 1
벤댕이                 1
뷔페                 14
생선회                 3
생선회/ 오징어회/ 세꼬시      1
생선회/초밥              1
세꼬시                 2
소바                  7
송어                  1
송어회                 4
알수없음                3
오꼬노미야끼              2
오코노미야끼              1
왕갈비                 1
우동                 28
우럭회                 1
이자카야/ 매콤크림새우        1
조개모듬구이              1
주점                  8
참치                  2
참치/ 참가자미            1
초밥                208
초밥/ 생연어             1
초밥/ 스시              5
카레/ 오야코동            1
해물요리                1
해물탕/ 회              1
해산물                 1
활어                  1
활어회                 9
활어회.매운탕             1
활어회/ 매운탕            1
회                 698
회/ 전복회              1
회무침                 1
회정식                 1
회집                 13
Name: storeid, dtype: int64

In [430]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('회') != -1)].index
df.loc[idxs, 'Category2'] = '회'

In [432]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('초밥') != -1)].index
df.loc[idxs, 'Category2'] = '초밥'

In [434]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('참치') != -1)].index
df.loc[idxs, 'Category2'] = '참치'

In [436]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('돈') != -1)].index
df.loc[idxs, 'Category2'] = '돈까스'

In [438]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('소바') != -1)].index
df.loc[idxs, 'Category2'] = '소바'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('국수') != -1)].index
df.loc[idxs, 'Category2'] = '소바'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('가라아게') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('도시락') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('동') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'

In [440]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('면') != -1)].index
df.loc[idxs, 'Category2'] = '소바'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('랍스타') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('벤댕이') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('해') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('참치') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('세꼬시') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('어') != -1)].index
df.loc[idxs, 'Category2'] = '회'

In [442]:
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('알수없음') != -1)].index
df.loc[idxs, 'Category2'] = '소바'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('조개') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('주점') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('야끼') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('이자') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일식') & (df.Category2.str.find('왕갈') != -1)].index
df.loc[idxs, 'Category2'] = '덮밥'

In [443]:
df[df.Category1 == '일식'].groupby('Category2').storeid.count()

Category2
덮밥      46
돈까스    140
라멘      18
뷔페      14
소바      12
초밥     214
회      757
Name: storeid, dtype: int64

### 서양식 카테고리 정제

In [444]:
df[df.Category1 == '서양식'].groupby('Category2').storeid.count()

Category2
그라탕                      1
꽃등심                      1
덮밥                       1
돈까스                      8
돈까스/ 스파게티                1
돈까스/ 초계국수                1
등갈비                      1
등심돈까스                    1
리조또/ 스테이크                1
맥주                       1
맥주/ 피자                   1
멕시코요리/ 타코/ 퀘사디아          1
버거/ 스테이크                 1
복합문화공간                   1
봉골레파스타                   1
뷔페                       3
브런치                      5
브런치/ 스테이크/ 스파게티          1
브런치/ 파니니/ 샐러드            1
비비큐                      1
비스트로                     1
샌드위치                     3
샐러드                      1
샐러드/ 스테이크                1
샐러드/ 파스타/ 스테이크           1
샐러드/ 파스타/ 스테이크/ 리조또      1
서양식코스요리                  1
수제버거                     3
숙박시설                     1
스테이크/ 파스타                2
                      ...
커피/ 아메리카노/ 라떼            1
커피/ 타르트                  1
커피/ 파스타                  1
큐브스테이크/ 와인               1
터키                     110
터키음식/ 케밥                 1
파니니/ 파스타                 1
파스타                     45
파스타/ 돈까스                 1
파스타/ 리조또/ 샐러드            1
파스타/ 물냉면                 1
파스타/ 스테이크                8
파스타/ 피자                  3
파스타/ 피자/ 스테이크            1
파스타/ 필라프                 1
팟타이/ 똠양꿍                 1
프랑스코스요리                  2
피자                     105
피자/ 리조또/ 맥주              1
피자/ 맥주                   1
피자/ 스테이크                 1
피자/ 파스타                  5
피자/ 파스타/ 리조또             2
피자집                      1
필라프                      1
하버돈가스                    1
함박스테이크                   5
핫도그                      1
햄버거                     30
화덕피자/ 수제파스타              1
Name: storeid, Length: 84, dtype: int64

In [445]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('파스타') != -1)].index
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('피자') != -1)].index
df.loc[idxs, 'Category2'] = '피자/ 파스타'

In [447]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('스페인') != -1)].index
df.loc[idxs, 'Category2'] = '스페인'

In [449]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('스테이크') != -1)].index
df.loc[idxs, 'Category2'] = '스테이크'

In [451]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('돈') != -1)].index
df.loc[idxs, 'Category2'] = '스테이크'

In [456]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('터키') != -1)].index
df.loc[idxs, 'Category2'] = '터키'

In [458]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('멕') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('필라프') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('스파게티') != -1)].index
df.loc[idxs, 'Category2'] = '피자/ 파스타'

In [462]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('브런치') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('커피') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('아메리') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('맥주') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('비스트로') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('이탈리안') != -1)].index
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('샌드위치') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('코스요리') != -1)].index
df.loc[idxs, 'Category2'] = '스테이크'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('와인') != -1)].index
df.loc[idxs, 'Category2'] = '스테이크'

In [466]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('핫도그') != -1)].index
df.loc[idxs, 'Category2'] = '햄버거'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('뷔페') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('그라탕') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('꽃등심') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('복합문화') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('덮밥') != -1)].index
df.loc[idxs, 'Category2'] = '터키'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('등갈비') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('버거') != -1)].index
df.loc[idxs, 'Category2'] = '햄버거'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('카레') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('비비큐') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('샐러드') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('치킨') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'

In [467]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('팟타이') != -1)].index
df.loc[idxs, 'Category1'] = '기타아시아식'
df.loc[idxs, 'Category2'] = '태국'

In [470]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('야끼') != -1)].index
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '덮밥'

In [472]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('숙박') != -1)].index
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('주류') != -1)].index
df.loc[idxs, 'Category2'] = '멕시코'

In [476]:
idxs = df[(df.Category1=='서양식') & (df.Category2.str.find('알수없음') != -1)].index
df.loc[idxs[:60],'Category2'] = '스페인'
df.loc[idxs[60:],'Category2'] = '멕시코'

In [477]:
df[df.Category1 == '서양식'].groupby('Category2').storeid.count()

Category2
멕시코         68
브런치         19
스테이크        34
스페인         62
터키         124
피자/ 파스타    198
햄버거         34
Name: storeid, dtype: int64

### 일반음식점 카테고리 정제

In [478]:
df[df.Category1 == '일반음식점'].groupby('Category2').storeid.count()

Category2
갈비              1
까페              8
대구머리찜           1
돼지구이            2
라이브카페           3
버거              1
분식              3
뷔페              5
사골옹심이           1
스테이크/ 파스타       1
스파게티            1
알수없음          165
이자카야            1
전통찻집            1
정종/대포집/소주방      6
패스트푸드           2
호프/통닭          14
회집              2
Name: storeid, dtype: int64

In [479]:
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('스파게티') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('패스트푸드') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '햄버거'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('버거') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '햄버거'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('파스타') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('페') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('뷔페') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '멕시코'

In [483]:
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('갈비') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('사골옹심이') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('대구') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '대구'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('분식') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '분식'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('회') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '회'

In [489]:
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('통닭') != -1)].index
df.loc[idxs, 'Category1'] = '치킨'
df.loc[idxs, 'Category2'] = '치킨'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('정종') != -1)].index
df.loc[idxs, 'Category1'] = '치킨'
df.loc[idxs, 'Category2'] = '치킨'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('돼지') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '돼지갈비'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('이자카야') != -1)].index
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('전통') != -1)].index
df.loc[idxs, 'Category1'] = '한식'

In [491]:
idxs = df[(df.Category1=='일반음식점') & (df.Category2.str.find('알수없음') != -1)].index
df.loc[idxs[:40], 'Category2'] = '불고기'
df.loc[idxs[40:80], 'Category2'] = '돼지구이'
df.loc[idxs[80:120], 'Category2'] = '숯불구이'
df.loc[idxs[120:], 'Category2'] = '전'

In [492]:
df[df.Category1 == '일반음식점'].groupby('Category2').storeid.count()

Series([], Name: storeid, dtype: int64)

### 치킨 카테고리 정제

In [493]:
df[df.Category1 == '치킨'].groupby('Category2').storeid.count()

Category2
닭강정              12
불닭                1
소머리국밥             1
찜닭/치킨/똥집          1
치밥                1
치킨              320
크리스피치킨/ 순살치킨      1
Name: storeid, dtype: int64

In [494]:
idxs = df[(df.Category1=='치킨') & (df.Category2.str.find('치') != -1)].index
df.loc[idxs, 'Category2'] = '치킨'

In [496]:
idxs = df[(df.Category1=='치킨') & (df.Category2.str.find('치') == -1)].index
df.loc[idxs, 'Category2'] = '닭강정'

In [497]:
df[df.Category1 == '치킨'].groupby('Category2').storeid.count()

Category2
닭강정     14
치킨     323
Name: storeid, dtype: int64

### 기타 카테고리 정제

In [498]:
df[df.Category1 == '기타'].groupby('Category2').storeid.count()

Category2
고기구이                        2
골뱅이무침                       1
과일주스                        1
까페                        120
꿀빵                          1
단란주점                        1
도넛                          4
돈카츠                         1
돼지고기구이/ 직화삼겹살/ 고등어김치찌개      1
디저트                         1
라이브카페                       1
막걸리/ 소고기전골                  1
맥주                          3
맥주/ 치킨                      1
맥주/ 한치                      1
미용실                         1
민속주점                        1
바게트                         1
반찬가게                        1
베이커리                        1
복어요리                        1
복어요리/ 복매운탕                  1
뷔페                        171
새우튀김                        2
생고기/ 육회/ 곱창전골               1
숙박시설                        3
아메리카노/ 단호박라떼                1
아메리카노/ 에스프레소                1
아메리카노/ 카페라떼                 1
아메리카노/ 쿠키                   1
                         ...
채식요리/ 불구이쌈밥                 1
치킨                          1
카페                        224
칵테일                         3
캠핑장                         1
커트                          1
커피                         14
커피/ 과일청/ 꿀빵                 1
커피/ 더치커피/ 자몽주스              1
커피/ 돈까스                     1
커피/ 돌체라떼                    1
커피/ 버거/ 샌드위치/ 샐러드           1
커피/ 브런치/ 토스트                1
커피/ 아메리카노/ 모히토              1
커피/ 아메리카노/ 크로와상샌드위치         1
커피/ 에스프레소/ 당근케이크            1
커피/ 에클레어                    1
커피프라푸치노                     1
타코                          1
테마파크                        2
토스트                        11
파스타/ 라따뚜이                   1
패스트푸드                       1
펜션                          1
포장마차                       22
포차                        201
풀빌라                         1
해물찜                         1
호프                         59
호프/통닭                      12
Name: storeid, Length: 74, dtype: int64

In [503]:
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('커피') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('아메') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('토스트') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('도넛') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('까페') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '브런치'

In [505]:
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('카페') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '카페'

In [511]:
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('호프') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('치킨') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('주점') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('골뱅이') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('주류') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('맥주') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '호프'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('포차') != -1)].index
df.loc[idxs, 'Category1'] = '기타'
df.loc[idxs, 'Category2'] = '포장마차'

In [527]:
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('고기구이') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '고기구이'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('과일') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('꿀빵') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('아이스크림') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('베이커리') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('미용') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('제과') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('펜션') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('빌라') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('바게트') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('유원지') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('반찬') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('캠핑') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('홀') != -1)].index
df.loc[idxs, 'Category2'] = '뷔페'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('숙박') != -1)].index
df.loc[idxs, 'Category2'] = '뷔페'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('테마') != -1)].index
df.loc[idxs, 'Category2'] = '디저트'

In [532]:
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('복어') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '복어'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('찌개') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('곱창') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '곱창'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('매운탕') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '매운탕'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('전골') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '전골'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('쌈밥') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '쌈밥'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('해물') != -1)].index
df.loc[idxs, 'Category1'] = '한식'
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('패스트') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '햄버거'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('타코') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('커트') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '멕시코'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('파스타') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('칵테일') != -1)].index
df.loc[idxs, 'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('돈카') != -1)].index
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('튀김') != -1)].index
df.loc[idxs, 'Category1'] = '일식'
df.loc[idxs, 'Category2'] = '덮밥'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('찻집') != -1)].index
df.loc[idxs, 'Category2'] = '카페'
idxs = df[(df.Category1=='기타') & (df.Category2.str.find('정종') != -1)].index
df.loc[idxs, 'Category2'] = '호프'

In [537]:
idxs = df[(df.Category1 == '기타') & (df.Category2 == '알수없음')].index
df.loc[idxs[:30], 'Category2'] = '호프'
df.loc[idxs[30:], 'Category2'] = '디저트'

In [538]:
df[df.Category1 == '기타'].groupby('Category2').storeid.count()

Category2
디저트      40
뷔페      176
카페      227
포장마차    223
호프      309
Name: storeid, dtype: int64

### 한식 카테고리 정제

In [571]:
korean_ca2_over10.index.sort_values()

Index(['갈비', '갈비탕', '감자탕', '감자탕집', '게', '경양식', '고기', '고기구이', '골뱅이', '곰탕', '곱창',
       '국밥', '국수', '김치찌개', '낙지', '냉면', '닭', '닭갈비', '닭발', '닭볶음탕', '도시락', '돼지',
       '돼지갈비', '돼지구이', '두루치기', '두부', '라면', '막창', '매운탕', '묵', '물회', '밀면', '바베큐',
       '반찬', '백반', '백숙', '버섯', '보리밥', '보신탕', '보쌈', '부대찌개', '분식', '불고기', '빈대떡',
       '삼겹살', '삼계탕', '생선', '생선구이', '생선조림', '샤브샤브', '설렁탕', '소고기', '소금구이', '수제비',
       '순대/순대국', '순두부', '숯불구이', '쌈밥', '아구찜', '알수없음', '야식집', '염소탕', '오리', '옻닭',
       '장어', '장어구이', '전', '조개', '족발/보쌈', '죽', '쭈꾸미', '찌개', '찜', '찜닭', '청국장',
       '추어탕', '코다리', '한정식', '해물', '해물요리', '해물찜', '해물탕', '해장국', '홍어', '회'],
      dtype='object', name='Category2')

In [555]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('묵은지') != -1)].index
df.loc[idxs, 'Category2'] = '김치찌개'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('부대') != -1)].index
df.loc[idxs, 'Category2'] = '부대찌개'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('생고기') != -1)].index
df.loc[idxs, 'Category2'] = '고기구이'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('육회') != -1)].index
df.loc[idxs, 'Category2'] = '한우/ 소고기'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('갈치조림') != -1)].index
df.loc[idxs, 'Category2'] = '생선조림'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('곱창') != -1)].index
df.loc[idxs, 'Category2'] = '곱창'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('김치찜') != -1)].index
df.loc[idxs, 'Category2'] = '김치찌개'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('국밥') != -1)].index
df.loc[idxs, 'Category2'] = '국밥'

In [557]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('불백') != -1)].index
df.loc[idxs, 'Category2'] = '불고기'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('껍데기') != -1)].index
df.loc[idxs, 'Category2'] = '고기구이'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('생태') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('갈치') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('황태') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('명태') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('대구') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('국수') != -1)].index
df.loc[idxs, 'Category2'] = '국수'

In [559]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('소고기') != -1)].index
df.loc[idxs, 'Category2'] = '소고기'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('해장국') != -1)].index
df.loc[idxs, 'Category2'] = '해장국'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('닭갈비') != -1)].index
df.loc[idxs, 'Category2'] = '닭갈비'

In [572]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('돼지구이') != -1)].index
df.loc[idxs, 'Category2'] = '돼지구이'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('꽃게') != -1)].index
df.loc[idxs, 'Category2'] = '꽃게'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('뚝배기') != -1)].index
df.loc[idxs, 'Category2'] = '국밥'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('두부전골') != -1)].index
df.loc[idxs, 'Category2'] = '두부'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('오징어') != -1)].index
df.loc[idxs, 'Category2'] = '오징어'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('동태탕') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('동태') != -1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('조개') != -1)].index
df.loc[idxs, 'Category2'] = '조개'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('갈매기살') != -1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('게') != -1)].index
df.loc[idxs, 'Category2'] = '게'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('숯불') != -1)].index
df.loc[idxs, 'Category2'] = '숯불구이'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('순두부') != -1)].index
df.loc[idxs, 'Category2'] = '순두부'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('생선회') != -1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('삼겹살') != -1)].index
df.loc[idxs, 'Category2'] = '삼겹살'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('오겹살') != -1)].index
df.loc[idxs, 'Category2'] = '삼겹살'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('닭곰탕') != -1)].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('등갈비') != -1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('매운탕') != -1)].index
df.loc[idxs, 'Category2'] = '매운탕'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('닭한') != -1)].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('주물럭') != -1)].index
df.loc[idxs, 'Category2'] = '삼겹살'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('영양탕') != -1)].index
df.loc[idxs, 'Category2'] = '육개장'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('닭볶음') != -1)].index
df.loc[idxs, 'Category2'] = '닭볶음탕'

In [575]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('굴') != -1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('해물요리') != -1)].index
df.loc[idxs, 'Category2'] = '해물'

In [577]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('족발') != -1)].index
df.loc[idxs, 'Category2'] = '족발/보쌈'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('해산물찜') != -1)].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('해물파전') != -1)].index
df.loc[idxs, 'Category2'] = '전'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('돼지고기') != -1)].index
df.loc[idxs, 'Category2'] = '돼지구이'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('생선찜') != -1)].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('코다리찜') != -1)].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('돼지갈비') != -1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('갈비찜') != -1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('양념불고기') != -1)].index
df.loc[idxs, 'Category2'] = '불고기'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('제육') != -1)].index
df.loc[idxs, 'Category2'] = '불고기'

In [579]:
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('순대') != -1)].index
df.loc[idxs, 'Category2'] = '순대/순대국'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('선지') != -1)].index
df.loc[idxs, 'Category2'] = '해장국'
idxs = df[(df.Category1=='한식') & (df.Category2.str.find('냉면') != -1)].index
df.loc[idxs, 'Category2'] = '냉면'
idxs = df[(df.Category1=='한식') & (df.Category2 == '면')].index
df.loc[idxs, 'Category2'] = '국수'

### 더 이상 카테고리를 일일이 정제할 수 없으므로 아직까지 카테고리2 분류를 하지 못한 것은 랜덤함수로 처리한다.

In [584]:
korean_ca2 = df[df.Category1 == '한식'].groupby('Category2').storeid.count().sort_values(ascending=False)

# 한식의 카테고리2 중, 식당의 수가 8~100개 사이인 것을 korean_random_category에 저장한다.
korean_ca2_over8 = korean_ca2[korean_ca2>=8]
korean_random_category = korean_ca2_over8[korean_ca2_over8<100]

In [588]:
from collections import defaultdict
random_dic = defaultdict(lambda x : 0)

In [594]:
# 랜덤으로 부여할 카테고리의 이름을 random_dic 에 인덱스와 함께 저장한다.
korean_random_category = korean_random_category.index.to_list()
for i in range(len(korean_random_category)):
    random_dic[korean_random_category[i]] = i

In [618]:
# random_dic의 key와 value값을 서로 바꾼다.
random_dic = dict(random_dic)
random_dic = {idx : cate for cate, idx in random_dic.items()}

In [622]:
random_dic

{0: '닭',
 1: '게',
 2: '추어탕',
 3: '해물',
 4: '삼계탕',
 5: '낙지',
 6: '한정식',
 7: '불고기',
 8: '돼지',
 9: '보리밥',
 10: '막창',
 11: '전',
 12: '쌈밥',
 13: '쭈꾸미',
 14: '생선구이',
 15: '숯불구이',
 16: '감자탕',
 17: '야식집',
 18: '죽',
 19: '도시락',
 20: '보쌈',
 21: '설렁탕',
 22: '두부',
 23: '순두부',
 24: '매운탕',
 25: '찌개',
 26: '조개',
 27: '곰탕',
 28: '샤브샤브',
 29: '찜닭',
 30: '해물탕',
 31: '바베큐',
 32: '해물찜',
 33: '청국장',
 34: '갈비탕',
 35: '보신탕',
 36: '반찬',
 37: '코다리',
 38: '감자탕집',
 39: '밀면',
 40: '생선조림',
 41: '육개장',
 42: '빈대떡',
 43: '버섯',
 44: '백숙',
 45: '홍어',
 46: '염소탕',
 47: '두루치기',
 48: '라면',
 49: '물회',
 50: '묵',
 51: '닭볶음탕',
 52: '찜',
 53: '소금구이',
 54: '수제비',
 55: '장어구이',
 56: '옻닭',
 57: '경양식',
 58: '골뱅이',
 59: '복어'}

In [601]:
# Category2 가 '알수없음'인 행들의 index를 unk_idxs 리스트에 담는다.
unk_idxs = df[df.Category2 == '알수없음'].index

In [611]:
# unk_idxs의 인덱스들에 각각 0~59까지의 랜덤 int 값을 부여한다.
unk_dic = defaultdict(lambda x: 0)
for idx in unk_idxs.to_list():
    unk_dic[idx] = np.random.randint(60)

In [615]:
# unk index, category index, category 이름을 저장할 데이터프레임을 생성한다.
unk_df = pd.DataFrame({
    'unk_idx' : unk_idxs
})
unk_df.head()

   unk_idx
0       44
1       53
2      103
3      114
4      128

In [616]:
# 각각의 index에 부여할 카테고리의 index를 매칭
unk_df['cate_idx'] = unk_df.unk_idx.map(unk_dic)
unk_df.head()

   unk_idx  cate_idx
0       44        26
1       53         8
2      103        23
3      114        13
4      128        58

In [623]:
# 카테고리 index에 맞는 카테고리의 이름을 category에 저장한다.
unk_df['category'] = unk_df.cate_idx.map(random_dic)
unk_df.head()

   unk_idx  cate_idx category
0       44        26       조개
1       53         8       돼지
2      103        23      순두부
3      114        13      쭈꾸미
4      128        58      골뱅이

In [627]:
# 가게리스트 df의 값을 바꾼다.
for idx, category in zip(unk_df.unk_idx, unk_df.category):
    df.loc[idx, 'Category2'] = category
    df.loc[idx, 'menu'] = category

In [679]:
ca2_korean[ca2_korean>=9].index.sort_values()

Index(['갈비', '갈비탕', '감자탕', '감자탕집', '게', '경양식', '고기', '고기구이', '골뱅이', '곰탕', '곱창',
       '국밥', '국수', '김치찌개', '낙지', '냉면', '닭', '닭갈비', '닭발', '닭볶음탕', '도시락', '돼지',
       '돼지구이', '두루치기', '두부', '라면', '막창', '매운탕', '묵', '물회', '밀면', '바베큐', '반찬',
       '백반', '버섯', '보리밥', '보신탕', '보쌈', '복어', '부대찌개', '분식', '불고기', '빈대떡', '삼겹살',
       '삼계탕', '생선', '샤브샤브', '설렁탕', '소고기', '소금구이', '수제비', '순대/순대국', '순두부',
       '숯불구이', '쌈밥', '아구찜', '야식집', '염소탕', '오리', '옻닭', '육개장', '장어', '전', '조개',
       '족발/보쌈', '죽', '쭈꾸미', '찌개', '찜', '찜닭', '청국장', '추어탕', '한정식', '해장국', '홍어',
       '회'],
      dtype='object', name='Category2')

In [648]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('꼬막')!=-1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '붕어찜')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '삼합')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '전골')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '오징어')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '파전')].index
df.loc[idxs, 'Category2'] = '전'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('해물')!=-1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('코다리')!=-1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('생선')!=-1)].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('갈빗살')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '소갈비')].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '양갈비')].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '양념갈비')].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '소불고기')].index
df.loc[idxs, 'Category2'] = '불고기'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '과메기')].index
df.loc[idxs, 'Category2'] = '생선'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '고등어조림')].index
df.loc[idxs, 'Category2'] = '생선조림'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('가정식')!=-1)].index
df.loc[idxs, 'Category2'] = '백반'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('버섯')!=-1)].index
df.loc[idxs, 'Category2'] = '버섯'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('똥집')!=-1)].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('양푼갈비')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('도토리')!=-1)].index
df.loc[idxs, 'Category2'] = '묵'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('갈비정식')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'

In [654]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('오리구이')!=-1)].index
df.loc[idxs, 'Category2'] = '오리'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('불고기')!=-1)].index
df.loc[idxs, 'Category2'] = '불고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('막창')!=-1)].index
df.loc[idxs, 'Category2'] = '막창'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('한우')!=-1)].index
df.loc[idxs, 'Category2'] = '소고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('등심')!=-1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('고기구이')!=-1)].index
df.loc[idxs, 'Category2'] = '고기구이'

In [661]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '비빔밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '돌솥밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '감자국')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '영양솥밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '섭국')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '곤드레밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '영양돌솥밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '사골')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '꼬리곰탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '곰치국')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '사철탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '도가니탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '모듬전')].index
df.loc[idxs, 'Category2'] = '전'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '김치두루치기두부')].index
df.loc[idxs, 'Category2'] = '김치찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('뼈다귀')!=-1)].index
df.loc[idxs, 'Category2'] = '해장국'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('전복')!=-1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('복어')!=-1)].index
df.loc[idxs, 'Category2'] = '복어'

In [673]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('백숙')!=-1)].index
df.loc[idxs, 'Category2'] = '삼계탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('전주비빔밥')!=-1)].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('주먹고기')!=-1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('돼지한마리')!=-1)].index
df.loc[idxs, 'Category2'] = '돼지구이'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('떡갈비')!=-1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('재육볶음')!=-1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('돈까스')!=-1)].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('왕갈비')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('오골계탕')!=-1)].index
df.loc[idxs, 'Category2'] = '삼계탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('옛날통닭')!=-1)].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('닭도리탕')!=-1)].index
df.loc[idxs, 'Category2'] = '닭볶음탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('장어')!=-1)].index
df.loc[idxs, 'Category2'] = '장어'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('생삼겹')!=-1)].index
df.loc[idxs, 'Category2'] = '삼겹살'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('생갈비')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('샤브샤브')!=-1)].index
df.loc[idxs, 'Category2'] = '샤브샤브'

In [671]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '내장탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '쏘가리탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '아나고탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '어복탕')].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('닭강정')!=-1)].index
df.loc[idxs, 'Category1'] = '치킨'
df.loc[idxs, 'Category2'] = '닭강정'

In [677]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('수제비')!=-1)].index
df.loc[idxs, 'Category2'] = '수제비'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('숯갈비')!=-1)].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('회춘탕')!=-1)].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('복탕')!=-1)].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('볼테기탕')!=-1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('뽈때기')!=-1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('뽈살')!=-1)].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('낙지')!=-1)].index
df.loc[idxs, 'Category2'] = '낙지'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('닭개장')!=-1)].index
df.loc[idxs, 'Category2'] = '닭볶음탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('닭꼬치')!=-1)].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('철판구이')!=-1)].index
df.loc[idxs, 'Category2'] = '고기구이'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('화로구이')!=-1)].index
df.loc[idxs, 'Category2'] = '고기구이'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('떡볶이')!=-1)].index
df.loc[idxs, 'Category2'] = '분식'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('모듬회')!=-1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('튀김')!=-1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('연어')!=-1)].index
df.loc[idxs, 'Category2'] = '회'

In [680]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('포장마차')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('칵테일')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('주점')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('포장마차')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('설렁탕')!=-1)].index
df.loc[idxs, 'Category2'] = '설렁탕'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('한정식')!=-1)].index
df.loc[idxs, 'Category2'] = '한정식'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('회덮밥')!=-1)].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('쌈밥')!=-1)].index
df.loc[idxs, 'Category2'] = '쌈밥'

In [682]:
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('두부김치')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('꼬치')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2.str.find('튀김')!=-1)].index
df.loc[idxs, 'Category2'] = '야식집'

In [686]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '모듬회')].index
df.loc[idxs, 'Category2'] = '회'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '잉어찜')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '장치찜')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '남도요리')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '다슬기')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '전골류')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '고래고기')].index
df.loc[idxs, 'Category2'] = '해물찜'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '민어탕')].index
df.loc[idxs, 'Category2'] = '해물'

In [688]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '해물찜')].index
df.loc[idxs, 'Category2'] = '찜'

In [692]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '인삼정식+삼계탕')].index
df.loc[idxs, 'Category2'] = '삼계탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '토종닭')].index
df.loc[idxs, 'Category2'] = '삼계탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '장닭')].index
df.loc[idxs, 'Category2'] = '삼계탕'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '새우구이')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '미역국')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '바지락죽')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '수수부꾸미')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '시골밥상')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '마늘약선정식')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '더덕정식')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '매생이국')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '불낙전골')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '물메기')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '옹심이')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '올갱이')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '오돌뼈')].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '불닭')].index
df.loc[idxs, 'Category2'] = '닭'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '흑염소전골')].index
df.loc[idxs, 'Category2'] = '염소탕'

In [694]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '밥버거')].index
df.loc[idxs, 'Category2'] = '분식'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '카페')].index
df.loc[idxs, 'Category2'] = '분식'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '골뱅이뱅뱅')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '맥주')].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '배춪ㄴ')].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '아이스크림호떡')].index
df.loc[idxs, 'Category2'] = '분식'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '짜글이찌개')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '된장찌개')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '도루묵/가자미찌개')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '계절정식')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '젓국갈비')].index
df.loc[idxs, 'Category2'] = '갈비'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '강된장')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '정식코스')].index
df.loc[idxs, 'Category2'] = '찌개'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '청국장정식')].index
df.loc[idxs, 'Category2'] = '찌개'

In [702]:
idxs = df[(df.Category1 == '한식')&(df.Category2 == '팔도면요리')].index
df.loc[idxs, 'Category2'] = '국수'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '팥죽')].index
df.loc[idxs, 'Category2'] = '죽'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '약쑥시레기밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '완당')].index
df.loc[idxs, 'Category2'] = '국수'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '대통밥')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '현미채식')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '약채밥상')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '머밀전병')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '메밀')].index
df.loc[idxs, 'Category2'] = '보리밥'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '연어덮밥/ 스테이크덮밥')].index
df.loc[idxs, 'Category2'] = '해물'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '월남쌈')].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '터키')].index
df.loc[idxs, 'Category2'] = '고기'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '파스타')].index
df.loc[idxs,'Category1'] = '서양식'
df.loc[idxs, 'Category2'] = '피자/ 파스타'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '호떡')].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '뷔페')].index
df.loc[idxs, 'Category2'] = '야식집'
idxs = df[(df.Category1 == '한식')&(df.Category2 == '전통찻집')].index
df.loc[idxs, 'Category2'] = '야식집'

## 카테고리 정제 완료

In [704]:
df.groupby(['Category1', 'Category2']).count()

                     storeid  Title  storename  Region  Sigungu  search_area  \
Category1 Category2
기타        디저트             40     40         40      40       40           40
          뷔페             176    176        176     176      176          176
          카페             227    227        227     227      227          227
          포장마차           223    223        223     223      223          223
          호프             309    309        309     309      309          309
기타아시아식    베트남             36     36         36      36       36           36
          인도              34     34         34      34       34           34
          태국               6      6          6       6        6            6
서양식       멕시코             70     70         70      70       70           70
          브런치            200    200        200     200      200          200
          스테이크            34     34         34      34       34           34
          스페인             62     62         62      62       62           62
          터키             124    124        124     124      124          124
          피자/ 파스타        205    205        205     205      205          205
          햄버거             38     38         38      38       38           38
일식        덮밥              51     51         51      51       51           51
          돈까스            140    140        140     140      140          140
          라멘              18     18         18      18       18           18
          뷔페              14     14         14      14       14           14
          소바              12     12         12      12       12           12
          초밥             214    214        214     214      214          214
          회              757    757        757     757      757          757
중국식       마라탕             12     12         12      12       12           12
          양꼬치             94     94         94      94       94           94
          짜장면             13     13         13      13       13           13
          짜장면/ 짬뽕        217    217        217     217      217          217
          탕수육             15     15         15      15       15           15
치킨        닭강정             17     17         17      17       17           17
          치킨             323    323        323     323      323          323
한식        갈비             390    390        390     390      390          390
...                      ...    ...        ...     ...      ...          ...
          설렁탕            182    182        182     182      182          182
          소고기            218    218        218     218      218          218
          소금구이           119    119        119     119      119          119
          수제비            117    117        117     117      117          117
          순대/순대국         326    326        326     326      326          326
          순두부            159    159        159     159      159          159
          숯불구이           183    183        183     183      183          183
          쌈밥             183    183        183     183      183          183
          아구찜            135    135        135     135      135          135
          야식집            197    197        197     197      197          197
          염소탕            126    126        126     126      126          126
          오리             189    189        189     189      189          189
          옻닭             118    118        118     118      118          118
          육개장            135    135        135     135      135          135
          장어             240    240        240     240      240          240
          전              179    179        179     179      179          179
          조개             128    128        128     128      128          128
          족발/보쌈          247    247        247     247      247          247
          죽              183    183        183     183      183          183
          쭈꾸미            174    174        174     174      174          174
          찌개             173    173        173     173      173          173
          찜              124    124        124     124      124          124
          찜닭             155    155        155     155      155          155
          청국장            135    135        135     135      135          135
          추어탕            204    204        204     204      204          204
          한정식            198    198        198     198      198          198
          해물              19     19         19      19       19           19
          해장국            162    162        162     162      162          162
          홍어             120    120        120     120      120          120
          회              167    167        167     167      167          167

                     menu  Blog  reviews_num
Category1 Category2
기타        디저트          40    40           40
          뷔페          176   176          176
          카페          227   227          227
          포장마차        223   223          223
          호프          309   309          309
기타아시아식    베트남          36    36           36
          인도           34    34           34
          태국            6     6            6
서양식       멕시코          70    70           70
          브런치         200   200          200
          스테이크         34    34           34
          스페인          62    62           62
          터키          124   124          124
          피자/ 파스타     205   205          205
          햄버거          38    38           38
일식        덮밥           51    51           51
          돈까스         140   140          140
          라멘           18    18           18
          뷔페           14    14           14
          소바           12    12           12
          초밥          214   214          214
          회           757   757          757
중국식       마라탕          12    12           12
          양꼬치          94    94           94
          짜장면          13    13           13
          짜장면/ 짬뽕     217   217          217
          탕수육          15    15           15
치킨        닭강정          17    17           17
          치킨          323   323          323
한식        갈비          390   390          390
...                   ...   ...          ...
          설렁탕         182   182          182
          소고기         218   218          218
          소금구이        119   119          119
          수제비         117   117          117
          순대/순대국      326   326          326
          순두부         159   159          159
          숯불구이        183   183          183
          쌈밥          183   183          183
          아구찜         135   135          135
          야식집         197   197          197
          염소탕         126   126          126
          오리          189   189          189
          옻닭          118   118          118
          육개장         135   135          135
          장어          240   240          240
          전           179   179          179
          조개          128   128          128
          족발/보쌈       247   247          247
          죽           183   183          183
          쭈꾸미         174   174          174
          찌개          173   173          173
          찜           124   124          124
          찜닭          155   155          155
          청국장         135   135          135
          추어탕         204   204          204
          한정식         198   198          198
          해물           19    19           19
          해장국         162   162          162
          홍어          120   120          120
          회           167   167          167

[106 rows x 9 columns]

In [16]:
df.to_csv('가게리스트_카테고리_최종.csv', encoding='utf-8')

In [26]:
df = pd.read_csv('./가게리스트_카테고리_최종.csv', index_col=0)

In [11]:
df[df.Category1=='한식'].Category2.sort_values().unique()

# 한식 Category2 리스트

array(['갈비', '갈비탕', '감자탕', '감자탕집', '게', '경양식', '고기', '고기구이', '골뱅이', '곰탕',
       '곱창', '국밥', '국수', '김치찌개', '낙지', '냉면', '닭', '닭갈비', '닭발', '닭볶음탕',
       '도시락', '돼지', '돼지구이', '두루치기', '두부', '라면', '막창', '매운탕', '묵', '물회',
       '밀면', '바베큐', '반찬', '백반', '버섯', '보리밥', '보신탕', '보쌈', '복어', '부대찌개',
       '분식', '불고기', '빈대떡', '삼겹살', '삼계탕', '생선', '샤브샤브', '설렁탕', '소고기',
       '소금구이', '수제비', '순대/순대국', '순두부', '숯불구이', '쌈밥', '아구찜', '야식집', '염소탕',
       '오리', '옻닭', '육개장', '장어', '전', '조개', '족발/보쌈', '죽', '쭈꾸미', '찌개', '찜',
       '찜닭', '청국장', '추어탕', '한정식', '해물', '해장국', '홍어', '회'], dtype=object)

In [21]:
df[df.Category1=='일식'].Category2.unique()

array(['덮밥', '일식 회', '돈까스', '초밥', '소바', '라멘', '일식뷔페'], dtype=object)

In [12]:
idxs = df[(df.Category1=='일식')&(df.Category2=='뷔페')].index
df.loc[idxs, 'Category2'] = '일식뷔페'

In [14]:
idxs = df[(df.Category1=='일식')&(df.Category2=='회')].index
df.loc[idxs, 'Category2'] = '일식 회'

In [4]:
df[df.Category2=='회'].Category1.unique()

array(['일식', '한식'], dtype=object)

In [6]:
df[df.Category2=='뷔페'].Category1.unique()

array(['기타', '일식'], dtype=object)

In [4]:
df.storeid.max()

183099

In [5]:
df.Region.unique()

array(['광주', '전라북도', '전라남도', '경기도', '서울', '대전', '인천', '경상북도', '제주도', '부산',
       '강원도', '경상남도', '울산', '대구', '충청북도', '충청남도'], dtype=object)

In [7]:
df.Sigungu.unique()

array(['광산구', '동구', '전주시', '완주군', '고창군', '광양시', '목포시', '여수시', '순천시',
       '나주시', '담양군', '곡성군', '고흥군', '화순군', '장흥군', '강진군', '해남군', '영암군',
       '무안군', '함평군', '영광군', '완도군', '익산시', '정읍시', '부안군', '군산시', '남원시',
       '김제시', '무주군', '순창군', '임실군', '진안군', '신안군', '평택시', '중랑구', '파주시',
       '수원시', '서구', '남양주시', '고양시', '화성시', '강화군', '용인시', '구리시', '연수구',
       '상주시', '중구', '양주시', '안양시', '의왕시', '동대문구', '성남시', '이천시', '경산시',
       '광주시', '제주시', '부평구', '기장군', '삼척시', '포천시', '안산시', '사상구', '강릉시',
       '의정부시', '미추홀구', '거제시', '성동구', '부천시', '양평군', '춘천시', '울주군', '하남시',
       '계양구', '안성시', '영도구', '유성구', '거창군', '군포시', '여주시', '동작구', '시흥시',
       '영덕군', '광명시', '속초시', '남동구', '정선군', '화천군', '오산시', '가평군', '창원시',
       '홍천군', '고성군', '강서구', '강남구', '함안군', '김해시', '김포시', '청주시', '동두천시',
       '함양군', '구미시', '양산시', '남구', '서초구', '북구', '과천시', '강동구', '서산시', '수정구',
       '옹진군', '보성군', '강북구', '원주시', '은평구', '광진구', '양천구', '용산구', '대덕구',
       '보령시', '평창군', '연천군', '남해군', '옥천군', '양구군', '부여군', '관악구', '통영시',
       '당진시', '연제구', '군위군', '창녕군', '영주시', '서귀포시', '진주시', '하동군', '제천시',
       '성북구', '문경시', '태백시', '예천군', '경주시', '계룡시', '달서구', '공주시', '해운대구',
       '합천군', '종로구', '괴산군', '구례군', '도봉구', '서대문구', '송파구', '금정구', '김천시',
       '양양군', '청송군', '사하구', '밀양시', '홍성군', '동해시', '노원구', '논산시', '단양군',
       '마포구', '동래구', '부산진구', '증평군', '울진군', '인제군', '영등포구', '사천시', '아산시',
       '천안시', '안동시', '포항시', '서천군', '보은군', '봉화군', '산청군', '영월군', '장수군',
       '수성구', '수영구', '충주시', '영천시', '예산군', '진도군', '음성군', '의령군', '의성군',
       '금산군', '장성군', '진천군', '철원군', '청도군', '칠곡군', '태안군', '횡성군'],
      dtype=object)

In [20]:
df.storename = df.storename.str.replace('\(주\)','')
df.storename = df.storename.str.replace('(','')
df.storename = df.storename.str.replace(')','')

In [22]:
dd = pd.DataFrame({
    'dd' : ['(d','dd)']
})

In [23]:
dd

    dd
0   (d
1  dd)

In [25]:
dd.dd.str.find('(')

0    0
1   -1
Name: dd, dtype: int64